name: FalloutWebserver
version: 2.1
description: Web server for the Fallout Bukkit plugin.
author: ampayne2
main: ninja.amp.falloutwebserver.FalloutWebserver
depend: [Fallout]
commands:
  falloutwebserver:
    aliases: [ fowebserver, falloutweb, foweb, fows, fow ]
